### ISSUE TITLE
Pointers for using Windows Configuration Designer command-line interface?

### ISSUE THREAD

**Issue by dmadisetti** [colebermudez/Windows-Deployment#8]
See: https://learn.microsoft.com/en-us/windows/configuration/provisioning-packages/provisioning-command-line

Just trying to figure out how I can easily tweak the ppkg process without having to go through a wizard each time

**Comment by colebermudez** [comment]
From what I can see, it looks like if you save the project from WCD, You can edit the XML directly and then create the PPKG from the CLI...or if you want to write the XML yourself you can.
